'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useToast } from '@/hooks/use-toast'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Anchor, Calendar, MapPin, User, Users, Ship, Printer, CheckCircle, XCircle } from 'lucide-react'
import { approveZarpe, rejectZarpe, approveCIMZarpe, rejectCIMZarpe, approveCaptainZarpe } from '@/app/actions/zarpe'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { getPortLabel } from '@/lib/ports'
import { useLanguage } from '@/lib/language-context'
import QRCode from 'qrcode'

interface ZarpeDisplayProps {
  zarpe: {
    id: number
    zarpe_number: string
    captain_name: string
    captain_passport: string
    captain_nationality: string
    crew_count: number
    passenger_count: number
    departure_date: string
    departure_time: string
    destination_country: string
    destination_port: string
    cargo_on_board: string | null
    export_manifest: string | null
    observations: string | null
    status: 'pending' | 'approved' | 'rejected'
    approved_by_name: string | null
    approved_at: string | null
    digital_signature: string | null
    cim_approved: boolean
    cim_approved_by: number | null
    cim_approved_at: string | null
    cim_comments: string | null
    cim_operator_name: string | null
    created_at: string
    vessel_flag: string | null
    vessel_length: number | null
    vessel_gt: number | null
    voyage_number: string | null
    last_port_name: string | null
    last_port_country: string | null
    port_of_arrival: string | null
    naviera_name: string | null
  }
  vesselName: string
  omiNumber: string
  canApprove?: boolean
  userRole?: string
}

export function ZarpeDisplay({ zarpe, vesselName, omiNumber, canApprove = false, userRole = '' }: ZarpeDisplayProps) {
  const router = useRouter()
  const { toast } = useToast()
  const { t } = useLanguage()
  const [loading, setLoading] = useState(false)
  const [rejectDialogOpen, setRejectDialogOpen] = useState(false)
  const [rejectReason, setRejectReason] = useState('')
  const [cimObservations, setCimObservations] = useState('')

  // Bilingual labels: Spanish / English
  const labels = {
    vesselName: `${t('zarpe.vesselName')} / Vessel Name`,
    omiNumber: `${t('zarpe.omiNumber')} / IMO Number`,
    flag: `${t('zarpe.flag')} / Flag`,
    length: `${t('zarpe.length')} / Length (m)`,
    gt: `${t('zarpe.gt')} / GT`,
    type: `${t('zarpe.type')} / Type`,
    captainName: `${t('zarpe.captainName')} / Captain Name`,
    passport: `${t('zarpe.passport')} / Passport`,
    nationality: `${t('zarpe.nationality')} / Nationality`,
    departurePort: `${t('zarpe.departurePort')} / Departure Port`,
    voyageNumber: `${t('zarpe.voyageNumber')} / Voyage Number`,
    destinationPort: `${t('zarpe.destinationPort')} / Destination Port`,
    departureDate: `${t('zarpe.departureDate')} / Departure Date`,
    departureTime: `${t('zarpe.departureTime')} / Departure Time`,
    provenance: `${t('zarpe.provenance')} / Provenance`,
    crew: `${t('zarpe.crew')} / Crew`,
    passengers: `${t('zarpe.passengers')} / Passengers`,
    cargo: `${t('zarpe.cargo')} / Cargo on Board`,
    shippingAgent: `${t('zarpe.shippingAgent')} / Shipping Agent`,
    cimOperator: `${t('zarpe.cimOperator')} / CIM Operator`,
    observations: `${t('zarpe.observations')} / Observations`,
    cimPreApproval: `${t('zarpe.cimPreApproval')} / CIM Pre-Approval`,
    portCaptain: `${t('zarpe.portCaptain')} / Port Captain`,
    cimOfficial: `${t('zarpe.cimOfficial')} / CIM Official`,
    authenticity: `${t('zarpe.authenticity')} / Authenticity Verification`,
    scanQR: `${t('zarpe.scanQR')} / Scan QR code to verify`,
    zarpeNo: `${t('zarpe.zarpeNo')} / Departure Permit No.`,
    issued: `${t('zarpe.issued')} / Issued`,
    approved: `${t('zarpe.approved')} / Approved`,
    vesselData: `${t('zarpe.vesselData')} / Vessel Data`,
    captainData: `${t('zarpe.captainData')} / Captain Data`,
    voyageData: `${t('zarpe.voyageData')} / Voyage Data`,
    otherData: `${t('zarpe.otherData')} / Other Data`,
    republic: `${t('zarpe.republic')} / Republic of Honduras`,
    maritime: `${t('zarpe.maritime')} / Merchant Marine Directorate`,
    zarpeTitle: `${t('zarpe.zarpeTitle')} / Port Departure`,
    generatedBy: `${t('zarpe.generatedBy')} / Generated by VUTMHN`,
    validWithQR: `${t('zarpe.validWithQR')} / This document is valid only with QR verification code`,
    noCargo: `${t('zarpe.noCargo')} / No cargo`,
  }

  const isCIMOfficer = userRole === 'oficial_cim'
  const isCaptain = userRole === 'capitan_puerto'
  const needsCIMApproval = !zarpe.cim_approved && zarpe.status === 'pending'
  const needsCaptainApproval = zarpe.cim_approved && zarpe.status === 'pending'

  const statusColors = {
    pending: { border: 'border-amber-300', bg: 'bg-amber-50', icon: 'text-amber-600', iconBg: 'bg-amber-100', badge: 'bg-amber-100 text-amber-800' },
    approved: { border: 'border-green-300', bg: 'bg-green-50', icon: 'text-green-600', iconBg: 'bg-green-100', badge: 'bg-green-100 text-green-800' },
    rejected: { border: 'border-red-300', bg: 'bg-red-50', icon: 'text-red-600', iconBg: 'bg-red-100', badge: 'bg-red-100 text-red-800' },
  }
  const colors = statusColors[zarpe.status] || statusColors.pending
  const statusLabels: Record<string, string> = { pending: 'Pendiente', approved: 'Aprobado', rejected: 'Rechazado' }

  async function handleCIMApprove() {
    setLoading(true)
    const result = await approveCIMZarpe(zarpe.id, cimObservations)
    if (result?.error) {
      toast({ title: 'Error', description: result.error, variant: 'destructive' })
    } else {
      toast({ title: 'Pre-aprobado por CIM', description: 'El zarpe ha sido pre-aprobado.' })
    }
    setLoading(false)
    router.refresh()
  }

  async function handleCIMReject() {
    if (!cimObservations.trim()) {
      toast({ title: 'Campo requerido', description: 'Debe indicar el motivo del rechazo', variant: 'destructive' })
      return
    }
    setLoading(true)
    const result = await rejectCIMZarpe(zarpe.id, cimObservations)
    if (result?.error) {
      toast({ title: 'Error', description: result.error, variant: 'destructive' })
    } else {
      toast({ title: 'Rechazado por CIM', description: 'El zarpe ha sido rechazado.', variant: 'destructive' })
    }
    setLoading(false)
    router.refresh()
  }

  async function handleCaptainApprove() {
    setLoading(true)
    const result = await approveCaptainZarpe(zarpe.id)
    if (result?.error) {
      toast({ title: 'Error', description: result.error, variant: 'destructive' })
    } else {
      toast({ title: 'Zarpe Aprobado', description: 'El zarpe ha sido aprobado por Capitanía.' })
    }
    setLoading(false)
    router.refresh()
  }

  async function handleReject() {
    if (!rejectReason.trim()) {
      toast({ title: 'Campo requerido', description: 'Debe indicar el motivo del rechazo', variant: 'destructive' })
      return
    }
    setLoading(true)
    const result = await rejectZarpe(zarpe.id, rejectReason)
    if (result?.error) {
      toast({ title: 'Error', description: result.error, variant: 'destructive' })
    } else {
      toast({ title: 'Zarpe Rechazado', description: 'El zarpe ha sido rechazado.', variant: 'destructive' })
    }
    setRejectDialogOpen(false)
    setLoading(false)
    router.refresh()
  }

  async function handlePrint() {
    const logoUrl = `${window.location.origin}/logo-vutm.jpg`
    // Ensure the zarpe number is properly encoded for the URL
    const zarpeNumberEncoded = encodeURIComponent(zarpe.zarpe_number)
    const verifyUrl = `${window.location.origin}/verificar/${zarpeNumberEncoded}`
    const portLabel = zarpe.port_of_arrival ? getPortLabel(zarpe.port_of_arrival) : 'N/A'
    
    // Generate QR code using client-side library (qrcode)
    let qrDataUrl = ''
    try {
      qrDataUrl = await QRCode.toDataURL(verifyUrl, {
        width: 200,
        margin: 1,
        color: {
          dark: '#000000',
          light: '#FFFFFF'
        }
      })
    } catch {
      qrDataUrl = ''
    }
    
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Zarpe ${zarpe.zarpe_number}</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, Helvetica, sans-serif; width: 210mm; min-height: 297mm; padding: 12mm 15mm; font-size: 11px; color: #1a1a1a; }
          .header { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin-bottom: 10px; }
          .header-logo { width: 60px; height: 60px; margin: 0 auto 4px; display: block; }
          .header h1 { font-size: 13px; color: #1e3a5f; letter-spacing: 1px; }
          .header h2 { font-size: 11px; font-weight: normal; color: #333; margin-top: 2px; }
          .header h3 { font-size: 14px; font-weight: bold; color: #1e3a5f; margin-top: 4px; letter-spacing: 2px; }
          .zarpe-number { font-size: 14px; font-weight: bold; margin-top: 4px; color: #1e3a5f; }
          .section { margin-bottom: 8px; }
          .section-title { font-weight: bold; font-size: 10px; color: #fff; background: #1e3a5f; padding: 3px 8px; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 1px; }
          .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 2px 12px; padding: 4px 8px; }
          .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 12px; padding: 4px 8px; }
          .field { margin-bottom: 3px; }
          .field-label { font-size: 8px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
          .field-value { font-size: 11px; font-weight: 600; }
          .signature-section { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 10px; padding-top: 8px; border-top: 1px solid #ccc; }
          .signature-box { text-align: center; }
          .signature-line { border-bottom: 1px solid #333; margin: 25px auto 4px; width: 80%; }
          .signature-label { font-size: 9px; color: #666; }
          .signature-name { font-size: 10px; font-weight: 600; }
          .qr-section { display: flex; align-items: center; justify-content: space-between; margin-top: 10px; padding: 8px; border: 1px solid #ddd; background: #f9f9f9; }
          .qr-text { font-size: 9px; color: #666; max-width: 60%; }
          .qr-text p { margin-bottom: 2px; }
          .qr-code img { width: 90px; height: 90px; }
          #qrcode { display: inline-block; }
          #qrcode img { width: 90px; height: 90px; }
          .footer { text-align: center; font-size: 8px; color: #999; margin-top: 8px; border-top: 1px solid #eee; padding-top: 4px; }
          .cim-approval { background: #f0f7ff; border: 1px solid #bdd6f5; padding: 6px 8px; margin-bottom: 8px; }
          .cim-label { font-size: 9px; color: #1e3a5f; font-weight: bold; text-transform: uppercase; }
          .cim-value { font-size: 10px; }
          @media print { 
            body { padding: 10mm 12mm; }
            @page { size: A4; margin: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <img src="${logoUrl}" alt="Logo" class="header-logo" />
          <h1>${labels.republic}</h1>
          <h2>${labels.maritime}</h2>
          <h3>${labels.zarpeTitle}</h3>
          <p class="zarpe-number">${labels.zarpeNo} ${zarpe.zarpe_number}</p>
        </div>

        <div class="section">
          <div class="section-title">${labels.vesselData}</div>
          <div class="grid-3">
            <div class="field"><div class="field-label">${labels.vesselName}</div><div class="field-value">${vesselName}</div></div>
            <div class="field"><div class="field-label">${labels.omiNumber}</div><div class="field-value">${omiNumber}</div></div>
            <div class="field"><div class="field-label">${labels.flag}</div><div class="field-value">${zarpe.vessel_flag || 'N/A'}</div></div>
            <div class="field"><div class="field-label">${labels.length}</div><div class="field-value">${zarpe.vessel_length || 'N/A'}</div></div>
            <div class="field"><div class="field-label">${labels.gt}</div><div class="field-value">${zarpe.vessel_gt || 'N/A'}</div></div>
            <div class="field"><div class="field-label">${labels.type}</div><div class="field-value">${vesselName}</div></div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">${labels.captainData}</div>
          <div class="grid-3">
            <div class="field"><div class="field-label">${labels.captainName}</div><div class="field-value">${zarpe.captain_name}</div></div>
            <div class="field"><div class="field-label">${labels.passport}</div><div class="field-value">${zarpe.captain_passport}</div></div>
            <div class="field"><div class="field-label">${labels.nationality}</div><div class="field-value">${zarpe.captain_nationality}</div></div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">${labels.voyageData}</div>
          <div class="grid-3">
            <div class="field"><div class="field-label">${labels.departurePort}</div><div class="field-value">${portLabel}</div></div>
            <div class="field"><div class="field-label">${labels.voyageNumber}</div><div class="field-value">${zarpe.voyage_number || 'N/A'}</div></div>
            <div class="field"><div class="field-label">${labels.destinationPort}</div><div class="field-value">${zarpe.destination_port}, ${zarpe.destination_country}</div></div>
            <div class="field"><div class="field-label">${labels.departureDate}</div><div class="field-value">${new Date(zarpe.departure_date).toLocaleDateString('es-HN')}</div></div>
            <div class="field"><div class="field-label">${labels.departureTime}</div><div class="field-value">${zarpe.departure_time}</div></div>
            <div class="field"><div class="field-label">${labels.provenance}</div><div class="field-value">${zarpe.last_port_name || 'N/A'}${zarpe.last_port_country ? ', ' + zarpe.last_port_country : ''}</div></div>
            <div class="field"><div class="field-label">${labels.crew}</div><div class="field-value">${zarpe.crew_count}</div></div>
            <div class="field"><div class="field-label">${labels.passengers}</div><div class="field-value">${zarpe.passenger_count || 0}</div></div>
            <div class="field"><div class="field-label">${labels.cargo}</div><div class="field-value">${zarpe.cargo_on_board || labels.noCargo}</div></div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">${labels.otherData}</div>
          <div class="grid-2">
            <div class="field"><div class="field-label">${labels.shippingAgent}</div><div class="field-value">${zarpe.naviera_name || 'N/A'}</div></div>
            <div class="field"><div class="field-label">${labels.cimOperator}</div><div class="field-value">${zarpe.cim_operator_name || 'N/A'}</div></div>
          </div>
          ${zarpe.observations ? `<div style="padding: 4px 8px;"><div class="field"><div class="field-label">${labels.observations}</div><div class="field-value">${zarpe.observations}</div></div></div>` : ''}
        </div>

        ${zarpe.cim_approved ? `
          <div class="cim-approval">
            <div class="cim-label">${labels.cimPreApproval}</div>
            <div class="cim-value">${labels.approved}: ${zarpe.cim_operator_name || 'N/A'} | ${labels.departureDate}: ${zarpe.cim_approved_at ? new Date(zarpe.cim_approved_at).toLocaleString('es-HN') : 'N/A'}</div>
            ${zarpe.cim_comments ? `<div class="cim-value">${labels.observations}: ${zarpe.cim_comments}</div>` : ''}
          </div>
        ` : ''}

        ${zarpe.status === 'approved' && zarpe.digital_signature ? `
          <div class="signature-section">
            <div class="signature-box">
              <div class="signature-line"></div>
              <div class="signature-name">${zarpe.approved_by_name || ''}</div>
              <div class="signature-label">${labels.portCaptain}</div>
              <div style="font-size:8px;color:#666;margin-top:2px;">Digital: ${zarpe.digital_signature.substring(0, 20)}...</div>
            </div>
            <div class="signature-box">
              <div class="signature-line"></div>
              <div class="signature-name">${zarpe.cim_operator_name || ''}</div>
              <div class="signature-label">${labels.cimOfficial}</div>
            </div>
          </div>
        ` : ''}

        <div class="qr-section">
          <div class="qr-text">
            <p><strong>${labels.authenticity}</strong></p>
            <p><a href="${verifyUrl}" target="_blank" style="color:#1e3a5f;text-decoration:underline;">${labels.scanQR} - Click here / clic aqui</a Haga></p>
            <p>${labels.zarpeNo} ${zarpe.zarpe_number}</p>
            <p style="word-break:break-all;font-size:7px;">${verifyUrl}</p>
            <p>${labels.issued}: ${new Date(zarpe.created_at).toLocaleString('es-HN')}</p>
            ${zarpe.approved_at ? `<p>${labels.approved}: ${new Date(zarpe.approved_at).toLocaleString('es-HN')}</p>` : ''}
          </div>
          <div class="qr-code">
            ${qrDataUrl ? `<a href="${verifyUrl}" target="_blank"><img src="${qrDataUrl}" alt="QR Code" style="cursor:pointer;width:90px;height:90px;" /></a>` : `<p style="font-size:10px;color:#999;">QR N/A</p>`}
            <p style="font-size:8px;margin-top:4px;text-align:center;"><a href="${verifyUrl}" target="_blank" style="color:#1e3a5f;">Verify / Verificar</a></p>
          </div>
  </div>
  
  <div class="footer">
  <p>${labels.generatedBy} - Ventanilla Unica de Transporte Maritimo de Honduras</p>
  <p>${labels.validWithQR}</p>
  </div>
  <script>window.onload = function() { window.print(); }</script>
  </body>
  </html>
  `
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(printContent)
      printWindow.document.close()
    }
  }

  return (
    <>
      <Card className={`${colors.border} ${colors.bg}`}>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className={`w-12 h-12 rounded-full flex items-center justify-center ${colors.iconBg}`}>
                <Anchor className={`w-6 h-6 ${colors.icon}`} />
              </div>
              <div>
                <CardTitle className="text-lg">Zarpe de Puerto</CardTitle>
                <CardDescription className="font-mono">{zarpe.zarpe_number}</CardDescription>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className={`inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ${colors.badge}`}>
                {statusLabels[zarpe.status]}
              </span>
              {zarpe.status === 'approved' && (
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="w-4 h-4 mr-1" />
                  Imprimir
                </Button>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Vessel Info */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="p-4 rounded-lg bg-white border border-slate-200">
              <div className="flex items-center gap-2 text-slate-500 mb-1">
                <Ship className="w-4 h-4" />
                <p className="text-sm">Buque</p>
              </div>
              <p className="font-semibold text-slate-900">{vesselName}</p>
              <p className="text-sm text-slate-500">OMI: {omiNumber}</p>
              {zarpe.vessel_flag && <p className="text-sm text-slate-500">Bandera: {zarpe.vessel_flag}</p>}
            </div>
            <div className="p-4 rounded-lg bg-white border border-slate-200">
              <div className="flex items-center gap-2 text-slate-500 mb-1">
                <User className="w-4 h-4" />
                <p className="text-sm">Capitán</p>
              </div>
              <p className="font-semibold text-slate-900">{zarpe.captain_name}</p>
              <p className="text-sm text-slate-500">Pasaporte: {zarpe.captain_passport}</p>
              <p className="text-sm text-slate-500">{zarpe.captain_nationality}</p>
            </div>
          </div>

          {/* Trip Info */}
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="p-4 rounded-lg bg-white border border-slate-200">
              <div className="flex items-center gap-2 text-slate-500 mb-1">
                <Calendar className="w-4 h-4" />
                <p className="text-sm">Salida</p>
              </div>
              <p className="font-semibold text-slate-900">{new Date(zarpe.departure_date).toLocaleDateString('es-HN')}</p>
              <p className="text-sm text-slate-500">{zarpe.departure_time}</p>
            </div>
            <div className="p-4 rounded-lg bg-white border border-slate-200">
              <div className="flex items-center gap-2 text-slate-500 mb-1">
                <MapPin className="w-4 h-4" />
                <p className="text-sm">Destino</p>
              </div>
              <p className="font-semibold text-slate-900">{zarpe.destination_port}</p>
              <p className="text-sm text-slate-500">{zarpe.destination_country}</p>
            </div>
            <div className="p-4 rounded-lg bg-white border border-slate-200">
              <div className="flex items-center gap-2 text-slate-500 mb-1">
                <Users className="w-4 h-4" />
                <p className="text-sm">Personas a Bordo</p>
              </div>
              <p className="font-semibold text-slate-900">{zarpe.crew_count} tripulantes</p>
              <p className="text-sm text-slate-500">{zarpe.passenger_count || 0} pasajeros</p>
            </div>
          </div>

          {/* CIM Approval Status */}
          {zarpe.cim_approved && (
            <div className="p-4 rounded-lg bg-blue-50 border border-blue-200">
              <div className="flex items-center gap-2 mb-1">
                <CheckCircle className="w-4 h-4 text-blue-600" />
                <p className="text-sm font-semibold text-blue-800">Pre-aprobado por CIM</p>
              </div>
              {zarpe.cim_operator_name && <p className="text-sm text-blue-700">Operador: {zarpe.cim_operator_name}</p>}
              {zarpe.cim_approved_at && <p className="text-sm text-blue-600">Fecha: {new Date(zarpe.cim_approved_at).toLocaleString('es-HN')}</p>}
              {zarpe.cim_comments && <p className="text-sm text-blue-700 mt-1">Observaciones: {zarpe.cim_comments}</p>}
            </div>
          )}

          {/* CIM Approval Form */}
          {canApprove && isCIMOfficer && needsCIMApproval && (
            <div className="p-4 rounded-lg bg-blue-50 border border-blue-200 space-y-3">
              <p className="font-semibold text-blue-800">Pre-Aprobacion CIM</p>
              <div>
                <Label htmlFor="cim-obs" className="text-sm text-blue-700">Observaciones</Label>
                <Textarea
                  id="cim-obs"
                  placeholder="Escriba sus observaciones aqui..."
                  value={cimObservations}
                  onChange={(e) => setCimObservations(e.target.value)}
                  className="mt-1 bg-white"
                />
              </div>
              <div className="flex gap-2">
                <Button onClick={handleCIMApprove} disabled={loading} className="bg-green-600 hover:bg-green-700 text-white">
                  <CheckCircle className="w-4 h-4 mr-1" />
                  Pre-Aprobar
                </Button>
                <Button onClick={handleCIMReject} disabled={loading} variant="destructive">
                  <XCircle className="w-4 h-4 mr-1" />
                  Rechazar
                </Button>
              </div>
            </div>
          )}

          {/* Captain Approval */}
          {canApprove && isCaptain && needsCaptainApproval && (
            <div className="p-4 rounded-lg bg-green-50 border border-green-200 space-y-3">
              <p className="font-semibold text-green-800">Aprobación Final - Capitanía de Puerto</p>
              <p className="text-sm text-green-700">El CIM ha pre-aprobado este zarpe. Proceda con la aprobación final.</p>
              <div className="flex gap-2">
                <Button onClick={handleCaptainApprove} disabled={loading} className="bg-green-600 hover:bg-green-700 text-white">
                  <CheckCircle className="w-4 h-4 mr-1" />
                  Aprobar Zarpe
                </Button>
                <Button onClick={() => setRejectDialogOpen(true)} disabled={loading} variant="destructive">
                  <XCircle className="w-4 h-4 mr-1" />
                  Rechazar
                </Button>
              </div>
            </div>
          )}

          {/* Captain waiting for CIM */}
          {canApprove && isCaptain && needsCIMApproval && (
            <div className="p-4 rounded-lg bg-amber-50 border border-amber-200">
              <p className="text-sm text-amber-800 font-medium">Esperando pre-aprobacion del CIM antes de poder aprobar este zarpe.</p>
            </div>
          )}

          {/* Approved info */}
          {zarpe.status === 'approved' && zarpe.approved_by_name && (
            <div className="p-4 rounded-lg bg-green-50 border border-green-200">
              <div className="flex items-center gap-2 mb-1">
                <CheckCircle className="w-4 h-4 text-green-600" />
                <p className="text-sm font-semibold text-green-800">Zarpe Aprobado</p>
              </div>
              <p className="text-sm text-green-700">Aprobado por: {zarpe.approved_by_name}</p>
              {zarpe.approved_at && <p className="text-sm text-green-600">Fecha: {new Date(zarpe.approved_at).toLocaleString('es-HN')}</p>}
              {zarpe.digital_signature && <p className="text-sm text-green-600 font-mono">Firma: {zarpe.digital_signature}</p>}
            </div>
          )}

          {/* Rejected info */}
          {zarpe.status === 'rejected' && zarpe.observations && (
            <div className="p-4 rounded-lg bg-red-50 border border-red-200">
              <div className="flex items-center gap-2 mb-1">
                <XCircle className="w-4 h-4 text-red-600" />
                <p className="text-sm font-semibold text-red-800">Zarpe Rechazado</p>
              </div>
              <p className="text-sm text-red-700">Motivo: {zarpe.observations}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Reject Dialog */}
      <Dialog open={rejectDialogOpen} onOpenChange={setRejectDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Rechazar Zarpe</DialogTitle>
            <DialogDescription>Indique el motivo del rechazo del zarpe.</DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label htmlFor="reject-reason">Motivo del Rechazo</Label>
            <Textarea
              id="reject-reason"
              placeholder="Escriba el motivo del rechazo..."
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setRejectDialogOpen(false)}>Cancelar</Button>
            <Button variant="destructive" onClick={handleReject} disabled={loading}>Rechazar</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
